version: '3.4'

services:
  handshakestheory.webapi:
    image: ${DOCKER_REGISTRY-}handshakestheorywebapi
    build:
      context: .
      dockerfile: HandshakesTheory.WebAPI/Dockerfile

  handshakestheory.site:
    image: ${DOCKER_REGISTRY-}handshakestheorysite
    build:
      context: .
      dockerfile: HandshakesTheory.Site/Dockerfile

