name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_icolors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'handshakestheory' }}
      run: |
        cd ./HandshakesTheory/HandshakesTheory.WebAPI
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a handshakestheory
        heroku container:release web -a handshakestheory
