name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          docker_compose_file: './docker-compose.yml'
          heroku_apps: '[{"imagename":"handshakestheorywebapi","appname":"handshakesapi","apptype":"web"}, {"imagename":"handshakestheorysite","appname":"handshakestheory","apptype":"web"}]'
